---
version: '2'
services:
# -------------------------------------------------------------------
  fivem:
    image: henkallsn/fivem_esx_bundle:mariadb-image
    stdin_open: true
    tty: true
    volumes:
      # Remember to change.
      - "/path/to/resources/folder:/config"
      # Remember to change.
      - "/path/to/txAdmin/config:/txData"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120"
    environment:
      SERVER_PROFILE: "default"
      # Remember to change.
      LICENCE_KEY: license-key-here
      FIVEM_PORT: 30120
      WEB_PORT: 40120
      HOST_UID: 1000
      HOST_GID: 100
      # Remember to change.
      FIVEM_HOSTNAME: hostname-to-fivem-server
      # Remember to change.
      STEAM_WEBAPIKEY: api-key-herer
      # Optional
      MARIADB_DATABASE_NAME: FiveMESX
      # Optional
      SQL_SERVER_NAME: mariadb
      # Please read note.
      MYSQL_ROOT_PASSWORD: password
# -------------------------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8100-8105:80
    environment:
      - PMA_HOST=fivem
    depends_on:
      - fivem
# -------------------------------------------------------------------
