version: '3'

services:
  fivem:
    image: andruida/fivem:latest
    container_name: fivem
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - "/path/to/resources/folder:/config"
      - "/path/to/txAdmin/config:/txData"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120"
    environment:
      SERVER_PROFILE: "default"
      LICENCE_KEY: "license-key-here"
      FIVEM_PORT: "30120"
      WEB_PORT: "40120"
      HOST_UID: 1000
      HOST_GID: 1000
      MARIADB_DATABASE_NAME: "name-of-database"
      FIVEM_HOSTNAME: "hostname-to-fivem-server"
      STEAM_WEBAPIKEY: "api-key-herer"
  mariadb:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
